### PR TITLE
BUG: streams needs to be generator, not list of generators

### PR DESCRIPTION
**Pull request by jrmlhermitte**
I tried it and it worked except for this line, thanks!

### CODE REVIEW

**Comment by jrmlhermitte** [comment]
There's a conflict. You need at some point to rebase on Dan's branch

**Comment by danielballan** [comment]
I'll manually merge to cherry-pick the changes that I like. :- ) Thanks everyone.

**Comment by CJ-Wright** [comment]
That was a design decision, we should support stream multiplexing. The `*` notation should have splayed the streams out into the args.

**Comment by jrmlhermitte** [comment]
thanks, I'll close this. What's the advantage of splaying the streams?

**Comment by CJ-Wright** [comment]
Many (I might even say most) of the important data analysis nodes (at least for my analysis) require more than one kind of data. For instance azimuthal integration requires 1) images, 2) a calibration, and 3) a mask (maybe). Each one of these might come from separate analysis steps thus their own stream. The function that does the integration should take each of these streams.

**Comment by CJ-Wright** [comment]
A good place to look where this kind of stuff has been done is [xpdAn](https://github.com/CJ-Wright/xpdAn/blob/799464fd587cc9cdfa6040933ce4c4c53d17fdca/xpdan/hfi.py)

**Comment by jrmlhermitte** [comment]
thanks, I see, I agree with you. I'm just not sure if we should have this in `event_map`. We need some kind of many to one demultiplexer. I imagined `event_map` was just a simple one to one beginning/example and that to expand we'd have to write a more careful different version. Not sure how to resolve this in a clean way as there are many ways to do this (for example, what do you do if the parameters you want are in the same stream?)
This may be a good discussion to have in person at some point. We're interested in getting something clean working for CMS as well.

**Comment by CJ-Wright** [comment]
I agree this needs its own separate decorator, and we need to make some design/API decisions as well for the `multi_event_map` or whatever we end up calling it. Part of the issue is also the denormalizing of the event stream itself, which I am slowly building a manifesto on [here](https://github.com/NSLS-II/databroker/pull/117#discussion_r97897996). Personally I would say to get each parameter from a separate stream (most likely via `itertools.tee`). This way if you ever end up deciding that you need secondary analysis before the multiplex step then you can slide one in without disrupting the other pieces of the pipeline.

Previously @danielballan and @tacaswell and I discussed this issue and decided to punt on it (hence the massive PR for xpdAn). We can always write out the header function interface (although really it is a stream function interface) the long way without the `event_map` decorator (or it's multi stream kin) and then build the decorator once we have a more firm idea of what needs to be implemented and how.

**Comment by jrmlhermitte** [comment]
Thanks, I'll refer to [that PR](https://github.com/NSLS-II/databroker/pull/117) to and we can log discussions there. I agree, it may be simpler to solve from the experimental end first, then @danielballan can decide what goes into databroker.

**Pull request closed without merging**
